console.log('\nRunning ./binarySearch\n---------\n')
require('./binarySearch')
console.log('---------\n')
console.log('\nRunning ./breadthFirstSearch\n---------\n')
require('./breadthFirstSearch')
console.log('---------\n')
console.log('\nRunning ./hashTables\n---------\n')
require('./hashTables')
console.log('---------\n')
console.log('\nRunning ./quickSort\n---------\n')
require('./quickSort')
console.log('---------\n')
console.log('\nRunning ./recursion\n---------\n')
require('./recursion')
console.log('---------\n')
